import { DOCUMENT_STATUSES } from './index.js';

const STATUS_FILTER_OPTIONS = [
  DOCUMENT_STATUSES.UNDER_REVIEW,
  DOCUMENT_STATUSES.NEEDS_ACTION,
  DOCUMENT_STATUSES.APPROVED,
  DOCUMENT_STATUSES.REJECTED,
  DOCUMENT_STATUSES.FOR_ARCHIVING,
  DOCUMENT_STATUSES.ARCHIVED,
];

/** Status dropdown options for the main Documents view (archive list uses full status list). */
export const DOCUMENT_VIEW_STATUS_FILTER_OPTIONS = STATUS_FILTER_OPTIONS.filter(
  (s) => s !== DOCUMENT_STATUSES.ARCHIVED
);
